// Generated by gencpp from file travel/node.msg
// DO NOT EDIT!


#ifndef TRAVEL_MESSAGE_NODE_H
#define TRAVEL_MESSAGE_NODE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>
#include <sensor_msgs/PointCloud2.h>
#include <sensor_msgs/PointCloud2.h>

namespace travel
{
template <class ContainerAllocator>
struct node_
{
  typedef node_<ContainerAllocator> Type;

  node_()
    : idx(0)
    , header()
    , pose()
    , lidar()
    , ground_estimate()  {
    }
  node_(const ContainerAllocator& _alloc)
    : idx(0)
    , header(_alloc)
    , pose(_alloc)
    , lidar(_alloc)
    , ground_estimate(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _idx_type;
  _idx_type idx;

   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _lidar_type;
  _lidar_type lidar;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _ground_estimate_type;
  _ground_estimate_type ground_estimate;





  typedef boost::shared_ptr< ::travel::node_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::travel::node_<ContainerAllocator> const> ConstPtr;

}; // struct node_

typedef ::travel::node_<std::allocator<void> > node;

typedef boost::shared_ptr< ::travel::node > nodePtr;
typedef boost::shared_ptr< ::travel::node const> nodeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::travel::node_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::travel::node_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::travel::node_<ContainerAllocator1> & lhs, const ::travel::node_<ContainerAllocator2> & rhs)
{
  return lhs.idx == rhs.idx &&
    lhs.header == rhs.header &&
    lhs.pose == rhs.pose &&
    lhs.lidar == rhs.lidar &&
    lhs.ground_estimate == rhs.ground_estimate;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::travel::node_<ContainerAllocator1> & lhs, const ::travel::node_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace travel

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::travel::node_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::travel::node_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::travel::node_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::travel::node_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::travel::node_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::travel::node_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::travel::node_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ffdb3dcfd475161209f2ce2c04a5bcc";
  }

  static const char* value(const ::travel::node_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ffdb3dcfd475161ULL;
  static const uint64_t static_value2 = 0x209f2ce2c04a5bccULL;
};

template<class ContainerAllocator>
struct DataType< ::travel::node_<ContainerAllocator> >
{
  static const char* value()
  {
    return "travel/node";
  }

  static const char* value(const ::travel::node_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::travel::node_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 idx\n"
"std_msgs/Header header\n"
"geometry_msgs/Pose pose\n"
"sensor_msgs/PointCloud2 lidar\n"
"sensor_msgs/PointCloud2 ground_estimate # estimate\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
;
  }

  static const char* value(const ::travel::node_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::travel::node_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.idx);
      stream.next(m.header);
      stream.next(m.pose);
      stream.next(m.lidar);
      stream.next(m.ground_estimate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct node_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::travel::node_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::travel::node_<ContainerAllocator>& v)
  {
    s << indent << "idx: ";
    Printer<int32_t>::stream(s, indent + "  ", v.idx);
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "lidar: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.lidar);
    s << indent << "ground_estimate: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.ground_estimate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRAVEL_MESSAGE_NODE_H
