<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>travel_ros</name>
  <version>1.0.0</version>
  <description>ROS 2 wrapper around the TRAVEL ground / above-ground object segmentation library.</description>

  <maintainer email="dhalsgh03@gmail.com">Minho Oh</maintainer>
  <maintainer email="egjung94@gmail.com">Euigon Jung</maintainer>
  <maintainer email="shapelim@mit.edu">Hyungtae Lim</maintainer>

  <license>GPL-3.0-or-later</license>

  <author email="dhalsgh03@gmail.com">Minho Oh</author>
  <author email="egjung94@gmail.com">Euigon Jung</author>
  <author email="shapelim@mit.edu">Hyungtae Lim</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>pcl_conversions</depend>
  <depend>libpcl-all-dev</depend>
  <depend>eigen</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
